config/routes.rb
Rails.application.routes.draw do
  resources :blogs
  devise_for :users
  root to: 'blogs#new'
  get 'others_blogs', to: 'blogs#others_blogs', as: :others_blogs
  get 'privacy_policy', to: 'homes#privacy_policy', as: :privacy_policy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  validates :title, presence: true

  enum status: { draft: 'draft', published: 'published' }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :blogs, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
# frozen_string_literal: true

class BlogsController < ApplicationController
  include Pagy::Backend
  before_action :authenticate_user!

  def index
    blogs = if params[:search].present?
              blogs = current_user.blogs
              sanitize_params = ActiveRecord::Base.send(:sanitize_sql_like, params[:search])
              blogs.where(
                'title ilike :q', q: "%#{sanitize_params}%"
              ).or(
                blogs.where('tags @> ARRAY[?]::varchar[]', [sanitize_params])
              ).or(
                blogs.where('content ilike ?', "%#{sanitize_params}%")
              ).order(updated_at: :desc)
            else
              current_user.blogs.order(updated_at: :desc)
            end
    @pagy_draft, @draft = pagy(blogs.draft)
    @pagy_published, @published = pagy(blogs.published, page_param: :page_published)
  end

  def new
    @blog = Blog.new
  end

  def create
    status = 'draft'
    status = 'published' if params[:status] == 'Publish'
    @blog = current_user.blogs.new(
      content: blog_params[:content],
      title: blog_params[:title],
      status: status,
      tags: blog_params[:tags].reject!(&:empty?) # remove empty string
    )
    if @blog.save
      if status == 'draft'
        flash[:success] = 'Success create draft.'
        redirect_to edit_blog_path(id: @blog.id)
      else
        flash[:success] = 'Success publish.'
        redirect_to new_blog_path
      end
    else
      render :new
    end
  end

  def edit
    @blog = current_user.blogs.find(params[:id])
    # NOTE: Dirty cheat to let select2 display the current tags
    @tags = @blog.tags.map { |value| [value, value] }
  end

  def update
    @blog = current_user.blogs.find(params[:id])
    status = 'draft'
    status = 'published' if params[:status] == 'Publish'
    clone_blog_params = blog_params
    clone_blog_params[:tags] = blog_params[:tags].reject!(&:empty?)
    clone_blog_params[:status] = status
    if @blog.update(clone_blog_params)
      flash[:success] = if status == 'draft'
                          'Success save draft.'
                        else
                          'Success publish.'
                        end
      redirect_to blogs_path
    else
      @tags = @blog.tags.map { |value| [value, value] }
      render :edit
    end
  end

  def show
    @blog = Blog.find_by(id: params[:id])
    @is_my_blog = @blog.user == current_user
  end

  def destroy
    @blog = current_user.blogs.find_by(id: params[:id])
    @blog.destroy
    flash[:success] = 'Success delete.'
    redirect_to blogs_path
  end

  def others_blogs
    others = Blog.where.not(user: current_user).published.includes(:user)
    @pagy, @others = pagy(others)
  end

  private

  def blog_params
    params.require(:blog).permit(:content, :title, :search, tags: [])
  end
end

app/controllers/homes_controller.rb
# frozen_string_literal: true

class HomesController < ApplicationController
  def privacy_policy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_markdown(content)
    Redcarpet::Markdown.new(
      BlogRender,
      no_intra_emphasis: true,
      fenced_code_blocks: true,
      disable_indented_code_blocks: true,
      autolink: true,
      tables: true,
      underline: true,
      highlight: true
    ).render(
      content
    ).html_safe
  end

  def render_nav_link(link_path, link_text)
    return nil if link_path != privacy_policy_path && current_user.blank?

    class_name = current_page?(link_path) ? 'nav-item active' : 'nav-item'
    if current_page?(root_path) && link_path == root_path
      class_name = 'nav-item active'
    end
    content_tag(
      :li, link_to(link_text, link_path, class: 'nav-link', method: :get),
      class: class_name
    )
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
  include Pagy::Frontend
end

app/views/blogs/_table.html.slim
div.table-responsive
  table.table.table-striped.table-sm
    thead.thead-dark
      tr
        th Title
        th Tags
        th Created
        th Modified
        th
        th

    tbody
      - local_assigns.fetch(:blogs).each do |blog|
        tr
          td = link_to blog.title, blog
          td = blog.tags.join(',').presence || '-'
          td = blog.created_at.strftime('%F %R')
          td = blog.updated_at.strftime('%F %R')
          td = link_to 'Edit', edit_blog_path(blog)
          td = link_to 'Destroy', blog, data: { confirm: 'Are you sure?' }, method: :delete

app/views/blogs/edit.html.slim
= form_for @blog do |f|
  - if @blog.errors.any?
    #error_explanation
      h2 = "#{pluralize(@blog.errors.count, "error")} prohibited this blog from being saved:"
      ul
        - @blog.errors.full_messages.each do |message|
          li = message

  .form-group
        = f.label :title, for: "blogTitle"
          | Title
        = f.text_field :title, id: 'blogTitle', class: 'form-control', autoFocus: true
  .field
    = f.label :tags
  = f.select :tags, @tags, {}, class: 'form-control select2-tags col-sm-12', multiple: "multiple"
  br
  = f.text_area :content, style: 'width: 100%; height: 50vh; font-size: 16px;', class: 'form-control'

  .row.justify-content-around
    .actions = f.submit name: 'status', value: 'Save as Draft', class: 'btn btn-primary btn-lg'
    .actions = f.submit name: 'status', value: 'Publish', class: 'btn btn-primary btn-lg'

h1 Current View

.card
  .card-body
    = render_markdown(@blog.content)

javascript:
  $(document).on("turbolinks:load", function() {
    tabOverride.set(document.getElementById('blog_content'));
    // TODO: this markdown toolbar will have multiple if not method: :get
    $('#blog_content').markdownToolbar();
    $(".select2-tags").select2({
      theme: "bootstrap",
      tags: true,
      tokenSeparators: [',', ' '],
    });
    // mi class crashed with material design icon class style
    $('.mi').addClass('markdown-mi').removeClass('mi');
  });

app/views/blogs/index.html.slim
h1 Draft blogs

== render 'table', blogs: @draft

div#pagy_draft
  == pagy_bootstrap_responsive_nav(@pagy_draft)

br

h1 Published blogs

== render 'table', blogs: @published

div#pagy_published
  == pagy_bootstrap_responsive_nav(@pagy_published)

javascript:
  $(document).on('turbolinks:load', function() {
    var pagy_draft = document.getElementById("pagy_draft");
    var pagy_published = document.getElementById("pagy_published");
    if (pagy_draft) {
      Pagy.init(pagy_draft);
    }
    if (pagy_published) {
      Pagy.init(pagy_published);
    }
  });

app/views/blogs/new.html.slim
= form_for @blog do |f|
  - if @blog.errors.any?
    #error_explanation
      h2 = "#{pluralize(@blog.errors.count, "error")} prohibited this blog from being saved:"
      ul
        - @blog.errors.full_messages.each do |message|
          li = message

  .form-group
    .floating-label
      = f.label :title, for: "blogTitle"
        | Title
      = f.text_field :title, id: 'blogTitle', class: 'form-control', autoFocus: true
  .field
    = f.label :tags
    = f.select :tags, [], {}, class: 'form-control select2-tags col-sm-12', multiple: "multiple"
  br
  = f.text_area :content, style: 'width: 100%; height: 50vh; font-size: 16px;', class: 'form-control'

  .row.justify-content-around
    .actions = f.submit name: 'status', value: 'Save as Draft', class: 'btn btn-primary btn-lg'
    .actions = f.submit name: 'status', value: 'Publish', class: 'btn btn-primary btn-lg'

javascript:
  $(document).on("turbolinks:load", function() {
    tabOverride.set(document.getElementById('blog_content'));
    $('#blog_content').markdownToolbar();
    $(".select2-tags").select2({
      theme: "bootstrap",
      tags: true,
      tokenSeparators: [',', ' ']
    });
  });

app/views/blogs/others_blogs.html.slim
h1 Others

div.table-responsive
  table.table.table-striped.table-sm
    thead.thead-dark
      tr
        th Title
        th Author
        th Tags
        th Created
        th Modified

    tbody
      - @others.each do |blog|
        tr
          td = link_to blog.title, blog
          td = blog.user.email
          td = blog.tags.join(',').presence || '-'
          td = blog.created_at.strftime('%F %R')
          td = blog.updated_at.strftime('%F %R')

== pagy_bootstrap_responsive_nav(@pagy)

javascript:
  $(document).on('turbolinks:load', function() {
    Pagy.init();
  });

app/views/blogs/show.html.slim
h1 = @blog.title
small = @blog.status.humanize
br
- @blog.tags.each do |tag|
  span.chip
    i.chip-icon
      = tag[0]
    = tag

.card
  .card-body
    = render_markdown(@blog.content)

- if @is_my_blog
  => link_to 'Edit', edit_blog_path(@blog)
  ' |
  => link_to 'Destroy', @blog, data: { confirm: 'Are you sure?' }, method: :delete

javascript:
  $(document).on("turbolinks:load", function() {
    $('.mi').addClass('markdown-mi').removeClass('mi');
  });

app/views/homes/privacy_policy.html.slim
h1
  | Privacy Policy
p
  | Effective date: April 03, 2019
p
  | CodeBlog ("us", "we", or "our") operates the https://markdown-code-blog.herokuapp.com/ website (hereinafter referred to as the "Service").
p
  | This page informs you of our policies regarding the collection, use, and disclosure of personal data when you use our Service and the choices you have associated with that data. The Privacy Policy for CodeBlog has been created with the help of
  a[href="https://termsfeed.com/privacy-policy/generator/"]
    | TermsFeed Privacy Policy Generator
  | .
p
  | We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions, accessible from https://markdown-code-blog.herokuapp.com/
h2
  | Definitions
ul
  li
    p
      strong
        | Service
    p
      | Service is the https://markdown-code-blog.herokuapp.com/ website operated by CodeBlog
  li
    p
      strong
        | Personal Data
    p
      | Personal Data means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).
  li
    p
      strong
        | Usage Data
    p
      | Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
  li
    p
      strong
        | Cookies
    p
      | Cookies are small files stored on your device (computer or mobile device).
h2
  | Information Collection and Use
p
  | We collect several different types of information for various purposes to provide and improve our Service to you.
h3
  | Types of Data Collected
h4
  | Personal Data
p
  | While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited to:
ul
  li
    | Email address
  li
    | Cookies and Usage Data
h4
  | Usage Data
p
  | We may also collect information how the Service is accessed and used ("Usage Data"). This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
h4
  | Tracking & Cookies Data
p
  | We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information.
p
  | Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyse our Service.
p
  | You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.
p
  | Examples of Cookies we use:
ul
  li
    strong
      | Session Cookies.
    |  We use Session Cookies to operate our Service.
  li
    strong
      | Preference Cookies.
    |  We use Preference Cookies to remember your preferences and various settings.
  li
    strong
      | Security Cookies.
    |  We use Security Cookies for security purposes.
h2
  | Use of Data
p
  | CodeBlog uses the collected data for various purposes:
ul
  li
    | To provide and maintain the Service
  li
    | To notify you about changes to our Service
  li
    | To allow you to participate in interactive features of our Service when you choose to do so
  li
    | To provide customer care and support
  li
    | To provide analysis or valuable information so that we can improve the Service
  li
    | To monitor the usage of the Service
  li
    | To detect, prevent and address technical issues
h2
  | Transfer Of Data
p
  | Your information, including Personal Data, may be transferred to - and maintained on - computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from your jurisdiction.
p
  | If you are located outside Malaysia and choose to provide information to us, please note that we transfer the data, including Personal Data, to Malaysia and process it there.
p
  | Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.
p
  | CodeBlog will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.
h2
  | Disclosure Of Data
h3
  | Legal Requirements
p
  | CodeBlog may disclose your Personal Data in the good faith belief that such action is necessary to:
ul
  li
    | To comply with a legal obligation
  li
    | To protect and defend the rights or property of CodeBlog
  li
    | To prevent or investigate possible wrongdoing in connection with the Service
  li
    | To protect the personal safety of users of the Service or the public
  li
    | To protect against legal liability
p
  | As an European citizen, under GDPR, you have certain individual rights. You can learn more about these guides in the
  a[href="https://termsfeed.com/blog/gdpr/#Individual_Rights_Under_the_GDPR"]
    | GDPR Guide
  | .
h2
  | Security of Data
p
  | The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.
h2
  | Service Providers
p
  | We may employ third party companies and individuals to facilitate our Service ("Service Providers"), to provide the Service on our behalf, to perform Service-related services or to assist us in analyzing how our Service is used.
p
  | These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.
h2
  | Links to Other Sites
p
  | Our Service may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.
p
  | We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
h2
  | Children's Privacy
p
  | Our Service does not address anyone under the age of 18 ("Children").
p
  | We do not knowingly collect personally identifiable information from anyone under the age of 18. If you are a parent or guardian and you are aware that your Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our servers.
h2
  | Changes to This Privacy Policy
p
  | We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.
p
  | We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update the "effective date" at the top of this Privacy Policy.
p
  | You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
h2
  | Contact Us
p
  | If you have any questions about this Privacy Policy, please contact us:
ul
  li
    | By email: vshy108@gmail.com

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | CodeBlog
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    meta content="initial-scale=1, shrink-to-fit=no, width=device-width" name="viewport"
  body
    nav.navbar.navbar-expand-lg.navbar-dark.bg-dark.sticky-top
      button.navbar-toggler[type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation"]
        span.navbar-toggler-icon
      #navbarTogglerDemo01.collapse.navbar-collapse
        = link_to "V", root_path, class:"navbar-brand"
        ul.navbar-nav.mr-auto.mt-2.mt-lg-0
          = render_nav_link(root_path, 'Home')
          = render_nav_link(blogs_path, 'Blog')
          = render_nav_link(others_blogs_path, "Others' Blog")
          = render_nav_link(privacy_policy_path, "Privacy Policy")
        - if current_user.present?
          = form_tag blogs_path, class: 'form-inline my-2 my-lg-0', method: :get
            = search_field_tag 'search', '', class: 'input form-control mr-sm-2', placeholder:"Title / Tags / Content", "aria-label":"Search", value: params[:search]
            = submit_tag 'Search', class: 'btn btn-outline-success my-2 my-sm-0'
        - if current_user.present?
          .dropdown
            button#dropdownMenu2.btn.btn-info.dropdown-toggle[type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"]
              =  current_user&.email
            .dropdown-menu.dropdown-menu-right[aria-labelledby="dropdownMenu2"]
              = button_to "Edit Profile", edit_user_registration_path, method: :get, class: 'dropdown-item'
              = button_to "Logout", destroy_user_session_path, method: :delete, class: 'dropdown-item', type: 'button'

    - if !flash.empty?
      - flash.each do |message_type, message|
        - if message_type == 'alert'
          = javascript_tag "toastr.warning('#{message}', '#{message_type.humanize}', {timeOut: 2000, closeButton: true, preventDuplicates: true, positionClass: 'toast-top-center'})"
        - elsif message_type == 'success'
          = javascript_tag "toastr.success('#{message}', '#{message_type.humanize}', {timeOut: 2000, closeButton: true, preventDuplicates: true, positionClass: 'toast-top-center'})"
        - elsif message_type == 'error'
          = javascript_tag "toastr.error('#{message}', '#{message_type.humanize}', {timeOut: 2000, closeButton: true, preventDuplicates: true, positionClass: 'toast-top-center'})"
        - else
          = javascript_tag "toastr.info('#{message}', '#{message_type.humanize}', {timeOut: 2000, closeButton: true, preventDuplicates: true, positionClass: 'toast-top-center'})"
      - flash.clear

    div style="padding: 12px;"
      = yield